### ISSUE TITLE
反馈两个小细节的错误

### ISSUE THREAD

**Issue by Bob8259** [lemonicy/clashpost#28]
1，实验助手介绍描述错误
错误页面：https://clashpost.com/upgrade/0800-Lab-Assistant
错误内容：
![image](https://github.com/user-attachments/assets/f08b796d-2547-4471-9ac2-d355f0b87259)
错误原因：药水名称错误。
应改正为：研究药水对实验助手无效。

2，熔岩气球玩偶介绍错误
错误页面：https://clashpost.com/upgrade/0785-Lavaloon-Puppet
错误内容：
![image](https://github.com/user-attachments/assets/d52bb4ad-92d9-460d-9e60-362f76c30e33)
错误原因：介绍内容缺失。
应改正为：* 在 2024 年 10 月的合体狂热活动中积攒 3 100 合体奖章（活动货币）后去商人那里购买即可解锁。自 2024/12/11 起，该装备有几率出现在商人那里，可花费 1 500 宝石购买。

以上是两个细节错误，因为有点懒，所以没有自己改。但是如果有需要的话，我可以fork一个repo,然后上传修改好的代码。非常感谢制作如此详细的网站，我也想为维护出一份力。

**Comment by lemonicy** [comment]
马上修改，等一会就会修复
